// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ARCANEWIRE_ARCANEWIRE_H_
#define FLATBUFFERS_GENERATED_ARCANEWIRE_ARCANEWIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ArcaneWire {

struct UUID;

struct Vec3Q;

struct EntityState;
struct EntityStateBuilder;
struct EntityStateT;

struct DeltaPayload;
struct DeltaPayloadBuilder;
struct DeltaPayloadT;

struct PlayerStatePayload;
struct PlayerStatePayloadBuilder;
struct PlayerStatePayloadT;

struct GameActionPayload;
struct GameActionPayloadBuilder;
struct GameActionPayloadT;

struct ClientFrame;
struct ClientFrameBuilder;
struct ClientFrameT;

struct ServerFrame;
struct ServerFrameBuilder;
struct ServerFrameT;

/// Client-to-server frame envelope.
enum ClientPayload : uint8_t {
  ClientPayload_NONE = 0,
  ClientPayload_PlayerState = 1,
  ClientPayload_Action = 2,
  ClientPayload_MIN = ClientPayload_NONE,
  ClientPayload_MAX = ClientPayload_Action
};

inline const ClientPayload (&EnumValuesClientPayload())[3] {
  static const ClientPayload values[] = {
    ClientPayload_NONE,
    ClientPayload_PlayerState,
    ClientPayload_Action
  };
  return values;
}

inline const char * const *EnumNamesClientPayload() {
  static const char * const names[4] = {
    "NONE",
    "PlayerState",
    "Action",
    nullptr
  };
  return names;
}

inline const char *EnumNameClientPayload(ClientPayload e) {
  if (::flatbuffers::IsOutRange(e, ClientPayload_NONE, ClientPayload_Action)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesClientPayload()[index];
}

template<typename T> struct ClientPayloadTraits {
  static const ClientPayload enum_value = ClientPayload_NONE;
};

template<> struct ClientPayloadTraits<ArcaneWire::PlayerStatePayload> {
  static const ClientPayload enum_value = ClientPayload_PlayerState;
};

template<> struct ClientPayloadTraits<ArcaneWire::GameActionPayload> {
  static const ClientPayload enum_value = ClientPayload_Action;
};

template<typename T> struct ClientPayloadUnionTraits {
  static const ClientPayload enum_value = ClientPayload_NONE;
};

template<> struct ClientPayloadUnionTraits<ArcaneWire::PlayerStatePayloadT> {
  static const ClientPayload enum_value = ClientPayload_PlayerState;
};

template<> struct ClientPayloadUnionTraits<ArcaneWire::GameActionPayloadT> {
  static const ClientPayload enum_value = ClientPayload_Action;
};

struct ClientPayloadUnion {
  ClientPayload type;
  void *value;

  ClientPayloadUnion() : type(ClientPayload_NONE), value(nullptr) {}
  ClientPayloadUnion(ClientPayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(ClientPayload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  ClientPayloadUnion(const ClientPayloadUnion &);
  ClientPayloadUnion &operator=(const ClientPayloadUnion &u)
    { ClientPayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  ClientPayloadUnion &operator=(ClientPayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~ClientPayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = ClientPayloadUnionTraits<RT>::enum_value;
    if (type != ClientPayload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, ClientPayload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  ArcaneWire::PlayerStatePayloadT *AsPlayerState() {
    return type == ClientPayload_PlayerState ?
      reinterpret_cast<ArcaneWire::PlayerStatePayloadT *>(value) : nullptr;
  }
  const ArcaneWire::PlayerStatePayloadT *AsPlayerState() const {
    return type == ClientPayload_PlayerState ?
      reinterpret_cast<const ArcaneWire::PlayerStatePayloadT *>(value) : nullptr;
  }
  ArcaneWire::GameActionPayloadT *AsAction() {
    return type == ClientPayload_Action ?
      reinterpret_cast<ArcaneWire::GameActionPayloadT *>(value) : nullptr;
  }
  const ArcaneWire::GameActionPayloadT *AsAction() const {
    return type == ClientPayload_Action ?
      reinterpret_cast<const ArcaneWire::GameActionPayloadT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyClientPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ClientPayload type);
template <bool B = false>
bool VerifyClientPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

/// Server-to-client frame envelope.
enum ServerPayload : uint8_t {
  ServerPayload_NONE = 0,
  ServerPayload_Delta = 1,
  ServerPayload_MIN = ServerPayload_NONE,
  ServerPayload_MAX = ServerPayload_Delta
};

inline const ServerPayload (&EnumValuesServerPayload())[2] {
  static const ServerPayload values[] = {
    ServerPayload_NONE,
    ServerPayload_Delta
  };
  return values;
}

inline const char * const *EnumNamesServerPayload() {
  static const char * const names[3] = {
    "NONE",
    "Delta",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerPayload(ServerPayload e) {
  if (::flatbuffers::IsOutRange(e, ServerPayload_NONE, ServerPayload_Delta)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerPayload()[index];
}

template<typename T> struct ServerPayloadTraits {
  static const ServerPayload enum_value = ServerPayload_NONE;
};

template<> struct ServerPayloadTraits<ArcaneWire::DeltaPayload> {
  static const ServerPayload enum_value = ServerPayload_Delta;
};

template<typename T> struct ServerPayloadUnionTraits {
  static const ServerPayload enum_value = ServerPayload_NONE;
};

template<> struct ServerPayloadUnionTraits<ArcaneWire::DeltaPayloadT> {
  static const ServerPayload enum_value = ServerPayload_Delta;
};

struct ServerPayloadUnion {
  ServerPayload type;
  void *value;

  ServerPayloadUnion() : type(ServerPayload_NONE), value(nullptr) {}
  ServerPayloadUnion(ServerPayloadUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(ServerPayload_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  ServerPayloadUnion(const ServerPayloadUnion &);
  ServerPayloadUnion &operator=(const ServerPayloadUnion &u)
    { ServerPayloadUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  ServerPayloadUnion &operator=(ServerPayloadUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~ServerPayloadUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = ServerPayloadUnionTraits<RT>::enum_value;
    if (type != ServerPayload_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, ServerPayload type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  ArcaneWire::DeltaPayloadT *AsDelta() {
    return type == ServerPayload_Delta ?
      reinterpret_cast<ArcaneWire::DeltaPayloadT *>(value) : nullptr;
  }
  const ArcaneWire::DeltaPayloadT *AsDelta() const {
    return type == ServerPayload_Delta ?
      reinterpret_cast<const ArcaneWire::DeltaPayloadT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyServerPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ServerPayload type);
template <bool B = false>
bool VerifyServerPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

/// 16-byte UUID as two uint64 halves (little-endian within each half).
/// Inline struct — no heap allocation, no vector offset overhead.
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) UUID FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t lo_;
  uint64_t hi_;

 public:
  UUID()
      : lo_(0),
        hi_(0) {
  }
  UUID(uint64_t _lo, uint64_t _hi)
      : lo_(::flatbuffers::EndianScalar(_lo)),
        hi_(::flatbuffers::EndianScalar(_hi)) {
  }
  uint64_t lo() const {
    return ::flatbuffers::EndianScalar(lo_);
  }
  uint64_t hi() const {
    return ::flatbuffers::EndianScalar(hi_);
  }
};
FLATBUFFERS_STRUCT_END(UUID, 16);

/// 3D position / velocity quantized to int16. Scale = 1.0 (one unit = one
/// i16 step). Range: +/- 32767 units per axis.
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Vec3Q FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x_;
  int16_t y_;
  int16_t z_;

 public:
  Vec3Q()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3Q(int16_t _x, int16_t _y, int16_t _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  int16_t x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  int16_t y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  int16_t z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3Q, 6);

struct EntityStateT : public ::flatbuffers::NativeTable {
  typedef EntityState TableType;
  std::unique_ptr<ArcaneWire::UUID> entity_id{};
  std::unique_ptr<ArcaneWire::UUID> cluster_id{};
  std::unique_ptr<ArcaneWire::Vec3Q> position{};
  std::unique_ptr<ArcaneWire::Vec3Q> velocity{};
  std::vector<uint8_t> user_data{};
  uint64_t client_seq = 0;
  EntityStateT() = default;
  EntityStateT(const EntityStateT &o);
  EntityStateT(EntityStateT&&) FLATBUFFERS_NOEXCEPT = default;
  EntityStateT &operator=(EntityStateT o) FLATBUFFERS_NOEXCEPT;
};

/// One entity's replicated state (spine + opaque user_data bytes).
/// Encoded as a standalone FlatBuffer, then embedded as raw bytes in
/// DeltaPayload.entity_data for chunk-assembly fan-out.
struct EntityState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityStateT NativeTableType;
  typedef EntityStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_CLUSTER_ID = 6,
    VT_POSITION = 8,
    VT_VELOCITY = 10,
    VT_USER_DATA = 12,
    VT_CLIENT_SEQ = 14
  };
  const ArcaneWire::UUID *entity_id() const {
    return GetStruct<const ArcaneWire::UUID *>(VT_ENTITY_ID);
  }
  const ArcaneWire::UUID *cluster_id() const {
    return GetStruct<const ArcaneWire::UUID *>(VT_CLUSTER_ID);
  }
  const ArcaneWire::Vec3Q *position() const {
    return GetStruct<const ArcaneWire::Vec3Q *>(VT_POSITION);
  }
  const ArcaneWire::Vec3Q *velocity() const {
    return GetStruct<const ArcaneWire::Vec3Q *>(VT_VELOCITY);
  }
  /// Opaque application-replicated state (typically JSON bytes).
  /// Absent or empty means "no user_data set."
  const ::flatbuffers::Vector<uint8_t> *user_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_USER_DATA);
  }
  /// Client-assigned sequence number echoed back for round-trip latency.
  /// Out-of-band — not part of the four-bucket entity model.
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<ArcaneWire::UUID>(verifier, VT_ENTITY_ID, 8) &&
           VerifyFieldRequired<ArcaneWire::UUID>(verifier, VT_CLUSTER_ID, 8) &&
           VerifyField<ArcaneWire::Vec3Q>(verifier, VT_POSITION, 2) &&
           VerifyField<ArcaneWire::Vec3Q>(verifier, VT_VELOCITY, 2) &&
           VerifyOffset(verifier, VT_USER_DATA) &&
           verifier.VerifyVector(user_data()) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           verifier.EndTable();
  }
  EntityStateT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EntityStateT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EntityState> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EntityStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EntityStateBuilder {
  typedef EntityState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(const ArcaneWire::UUID *entity_id) {
    fbb_.AddStruct(EntityState::VT_ENTITY_ID, entity_id);
  }
  void add_cluster_id(const ArcaneWire::UUID *cluster_id) {
    fbb_.AddStruct(EntityState::VT_CLUSTER_ID, cluster_id);
  }
  void add_position(const ArcaneWire::Vec3Q *position) {
    fbb_.AddStruct(EntityState::VT_POSITION, position);
  }
  void add_velocity(const ArcaneWire::Vec3Q *velocity) {
    fbb_.AddStruct(EntityState::VT_VELOCITY, velocity);
  }
  void add_user_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> user_data) {
    fbb_.AddOffset(EntityState::VT_USER_DATA, user_data);
  }
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(EntityState::VT_CLIENT_SEQ, client_seq, 0);
  }
  explicit EntityStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityState>(end);
    fbb_.Required(o, EntityState::VT_ENTITY_ID);
    fbb_.Required(o, EntityState::VT_CLUSTER_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityState> CreateEntityState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    const ArcaneWire::UUID *cluster_id = nullptr,
    const ArcaneWire::Vec3Q *position = nullptr,
    const ArcaneWire::Vec3Q *velocity = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> user_data = 0,
    uint64_t client_seq = 0) {
  EntityStateBuilder builder_(_fbb);
  builder_.add_client_seq(client_seq);
  builder_.add_user_data(user_data);
  builder_.add_velocity(velocity);
  builder_.add_position(position);
  builder_.add_cluster_id(cluster_id);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EntityState> CreateEntityStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    const ArcaneWire::UUID *cluster_id = nullptr,
    const ArcaneWire::Vec3Q *position = nullptr,
    const ArcaneWire::Vec3Q *velocity = nullptr,
    const std::vector<uint8_t> *user_data = nullptr,
    uint64_t client_seq = 0) {
  auto user_data__ = user_data ? _fbb.CreateVector<uint8_t>(*user_data) : 0;
  return ArcaneWire::CreateEntityState(
      _fbb,
      entity_id,
      cluster_id,
      position,
      velocity,
      user_data__,
      client_seq);
}

::flatbuffers::Offset<EntityState> CreateEntityState(::flatbuffers::FlatBufferBuilder &_fbb, const EntityStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DeltaPayloadT : public ::flatbuffers::NativeTable {
  typedef DeltaPayload TableType;
  std::unique_ptr<ArcaneWire::UUID> source_cluster_id{};
  int64_t seq = 0;
  uint64_t tick = 0;
  double timestamp = 0.0;
  std::vector<uint8_t> entity_data{};
  std::vector<uint32_t> entity_offsets{};
  std::vector<ArcaneWire::UUID> removed{};
  DeltaPayloadT() = default;
  DeltaPayloadT(const DeltaPayloadT &o);
  DeltaPayloadT(DeltaPayloadT&&) FLATBUFFERS_NOEXCEPT = default;
  DeltaPayloadT &operator=(DeltaPayloadT o) FLATBUFFERS_NOEXCEPT;
};

/// Server -> client: snapshot of entity updates + removals for one tick.
///
/// Entity encoding uses the concatenated-chunks pattern for fan-out:
/// the server pre-encodes each EntityState once per tick as a standalone
/// FlatBuffer, then concatenates the relevant subset per subscriber into
/// entity_data. entity_offsets records where each entity's bytes start.
///
/// Decode path: for entity i, slice entity_data[entity_offsets[i] ..
/// entity_offsets[i+1]] (or end of entity_data for the last entity),
/// then flatbuffers::root::<EntityState>(slice).
struct DeltaPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeltaPayloadT NativeTableType;
  typedef DeltaPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE_CLUSTER_ID = 4,
    VT_SEQ = 6,
    VT_TICK = 8,
    VT_TIMESTAMP = 10,
    VT_ENTITY_DATA = 12,
    VT_ENTITY_OFFSETS = 14,
    VT_REMOVED = 16
  };
  const ArcaneWire::UUID *source_cluster_id() const {
    return GetStruct<const ArcaneWire::UUID *>(VT_SOURCE_CLUSTER_ID);
  }
  int64_t seq() const {
    return GetField<int64_t>(VT_SEQ, 0);
  }
  uint64_t tick() const {
    return GetField<uint64_t>(VT_TICK, 0);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  /// Concatenated standalone-FlatBuffer-encoded EntityState bytes.
  const ::flatbuffers::Vector<uint8_t> *entity_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_ENTITY_DATA);
  }
  /// Byte offset of each entity within entity_data.
  const ::flatbuffers::Vector<uint32_t> *entity_offsets() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_ENTITY_OFFSETS);
  }
  /// Entities removed this tick.
  const ::flatbuffers::Vector<const ArcaneWire::UUID *> *removed() const {
    return GetPointer<const ::flatbuffers::Vector<const ArcaneWire::UUID *> *>(VT_REMOVED);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<ArcaneWire::UUID>(verifier, VT_SOURCE_CLUSTER_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_SEQ, 8) &&
           VerifyField<uint64_t>(verifier, VT_TICK, 8) &&
           VerifyField<double>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_ENTITY_DATA) &&
           verifier.VerifyVector(entity_data()) &&
           VerifyOffset(verifier, VT_ENTITY_OFFSETS) &&
           verifier.VerifyVector(entity_offsets()) &&
           VerifyOffset(verifier, VT_REMOVED) &&
           verifier.VerifyVector(removed()) &&
           verifier.EndTable();
  }
  DeltaPayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DeltaPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DeltaPayload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeltaPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DeltaPayloadBuilder {
  typedef DeltaPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source_cluster_id(const ArcaneWire::UUID *source_cluster_id) {
    fbb_.AddStruct(DeltaPayload::VT_SOURCE_CLUSTER_ID, source_cluster_id);
  }
  void add_seq(int64_t seq) {
    fbb_.AddElement<int64_t>(DeltaPayload::VT_SEQ, seq, 0);
  }
  void add_tick(uint64_t tick) {
    fbb_.AddElement<uint64_t>(DeltaPayload::VT_TICK, tick, 0);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(DeltaPayload::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_entity_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> entity_data) {
    fbb_.AddOffset(DeltaPayload::VT_ENTITY_DATA, entity_data);
  }
  void add_entity_offsets(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> entity_offsets) {
    fbb_.AddOffset(DeltaPayload::VT_ENTITY_OFFSETS, entity_offsets);
  }
  void add_removed(::flatbuffers::Offset<::flatbuffers::Vector<const ArcaneWire::UUID *>> removed) {
    fbb_.AddOffset(DeltaPayload::VT_REMOVED, removed);
  }
  explicit DeltaPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeltaPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeltaPayload>(end);
    fbb_.Required(o, DeltaPayload::VT_SOURCE_CLUSTER_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<DeltaPayload> CreateDeltaPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *source_cluster_id = nullptr,
    int64_t seq = 0,
    uint64_t tick = 0,
    double timestamp = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> entity_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> entity_offsets = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const ArcaneWire::UUID *>> removed = 0) {
  DeltaPayloadBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_tick(tick);
  builder_.add_seq(seq);
  builder_.add_removed(removed);
  builder_.add_entity_offsets(entity_offsets);
  builder_.add_entity_data(entity_data);
  builder_.add_source_cluster_id(source_cluster_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeltaPayload> CreateDeltaPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *source_cluster_id = nullptr,
    int64_t seq = 0,
    uint64_t tick = 0,
    double timestamp = 0.0,
    const std::vector<uint8_t> *entity_data = nullptr,
    const std::vector<uint32_t> *entity_offsets = nullptr,
    const std::vector<ArcaneWire::UUID> *removed = nullptr) {
  auto entity_data__ = entity_data ? _fbb.CreateVector<uint8_t>(*entity_data) : 0;
  auto entity_offsets__ = entity_offsets ? _fbb.CreateVector<uint32_t>(*entity_offsets) : 0;
  auto removed__ = removed ? _fbb.CreateVectorOfStructs<ArcaneWire::UUID>(*removed) : 0;
  return ArcaneWire::CreateDeltaPayload(
      _fbb,
      source_cluster_id,
      seq,
      tick,
      timestamp,
      entity_data__,
      entity_offsets__,
      removed__);
}

::flatbuffers::Offset<DeltaPayload> CreateDeltaPayload(::flatbuffers::FlatBufferBuilder &_fbb, const DeltaPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PlayerStatePayloadT : public ::flatbuffers::NativeTable {
  typedef PlayerStatePayload TableType;
  std::unique_ptr<ArcaneWire::UUID> entity_id{};
  std::unique_ptr<ArcaneWire::Vec3Q> position{};
  std::unique_ptr<ArcaneWire::Vec3Q> velocity{};
  std::vector<uint8_t> user_data{};
  uint64_t client_seq = 0;
  PlayerStatePayloadT() = default;
  PlayerStatePayloadT(const PlayerStatePayloadT &o);
  PlayerStatePayloadT(PlayerStatePayloadT&&) FLATBUFFERS_NOEXCEPT = default;
  PlayerStatePayloadT &operator=(PlayerStatePayloadT o) FLATBUFFERS_NOEXCEPT;
};

/// Client -> server: player pushing own entity spine + optional user_data.
struct PlayerStatePayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerStatePayloadT NativeTableType;
  typedef PlayerStatePayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_POSITION = 6,
    VT_VELOCITY = 8,
    VT_USER_DATA = 10,
    VT_CLIENT_SEQ = 12
  };
  const ArcaneWire::UUID *entity_id() const {
    return GetStruct<const ArcaneWire::UUID *>(VT_ENTITY_ID);
  }
  const ArcaneWire::Vec3Q *position() const {
    return GetStruct<const ArcaneWire::Vec3Q *>(VT_POSITION);
  }
  const ArcaneWire::Vec3Q *velocity() const {
    return GetStruct<const ArcaneWire::Vec3Q *>(VT_VELOCITY);
  }
  const ::flatbuffers::Vector<uint8_t> *user_data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_USER_DATA);
  }
  /// Client-assigned sequence number for round-trip latency measurement.
  uint64_t client_seq() const {
    return GetField<uint64_t>(VT_CLIENT_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<ArcaneWire::UUID>(verifier, VT_ENTITY_ID, 8) &&
           VerifyField<ArcaneWire::Vec3Q>(verifier, VT_POSITION, 2) &&
           VerifyField<ArcaneWire::Vec3Q>(verifier, VT_VELOCITY, 2) &&
           VerifyOffset(verifier, VT_USER_DATA) &&
           verifier.VerifyVector(user_data()) &&
           VerifyField<uint64_t>(verifier, VT_CLIENT_SEQ, 8) &&
           verifier.EndTable();
  }
  PlayerStatePayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PlayerStatePayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PlayerStatePayload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerStatePayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PlayerStatePayloadBuilder {
  typedef PlayerStatePayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(const ArcaneWire::UUID *entity_id) {
    fbb_.AddStruct(PlayerStatePayload::VT_ENTITY_ID, entity_id);
  }
  void add_position(const ArcaneWire::Vec3Q *position) {
    fbb_.AddStruct(PlayerStatePayload::VT_POSITION, position);
  }
  void add_velocity(const ArcaneWire::Vec3Q *velocity) {
    fbb_.AddStruct(PlayerStatePayload::VT_VELOCITY, velocity);
  }
  void add_user_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> user_data) {
    fbb_.AddOffset(PlayerStatePayload::VT_USER_DATA, user_data);
  }
  void add_client_seq(uint64_t client_seq) {
    fbb_.AddElement<uint64_t>(PlayerStatePayload::VT_CLIENT_SEQ, client_seq, 0);
  }
  explicit PlayerStatePayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerStatePayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerStatePayload>(end);
    fbb_.Required(o, PlayerStatePayload::VT_ENTITY_ID);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerStatePayload> CreatePlayerStatePayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    const ArcaneWire::Vec3Q *position = nullptr,
    const ArcaneWire::Vec3Q *velocity = nullptr,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> user_data = 0,
    uint64_t client_seq = 0) {
  PlayerStatePayloadBuilder builder_(_fbb);
  builder_.add_client_seq(client_seq);
  builder_.add_user_data(user_data);
  builder_.add_velocity(velocity);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlayerStatePayload> CreatePlayerStatePayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    const ArcaneWire::Vec3Q *position = nullptr,
    const ArcaneWire::Vec3Q *velocity = nullptr,
    const std::vector<uint8_t> *user_data = nullptr,
    uint64_t client_seq = 0) {
  auto user_data__ = user_data ? _fbb.CreateVector<uint8_t>(*user_data) : 0;
  return ArcaneWire::CreatePlayerStatePayload(
      _fbb,
      entity_id,
      position,
      velocity,
      user_data__,
      client_seq);
}

::flatbuffers::Offset<PlayerStatePayload> CreatePlayerStatePayload(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerStatePayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GameActionPayloadT : public ::flatbuffers::NativeTable {
  typedef GameActionPayload TableType;
  std::unique_ptr<ArcaneWire::UUID> entity_id{};
  std::string action_type{};
  std::vector<uint8_t> payload{};
  GameActionPayloadT() = default;
  GameActionPayloadT(const GameActionPayloadT &o);
  GameActionPayloadT(GameActionPayloadT&&) FLATBUFFERS_NOEXCEPT = default;
  GameActionPayloadT &operator=(GameActionPayloadT o) FLATBUFFERS_NOEXCEPT;
};

/// Client -> server: game action routed through the cluster's action channel.
struct GameActionPayload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameActionPayloadT NativeTableType;
  typedef GameActionPayloadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_ACTION_TYPE = 6,
    VT_PAYLOAD = 8
  };
  const ArcaneWire::UUID *entity_id() const {
    return GetStruct<const ArcaneWire::UUID *>(VT_ENTITY_ID);
  }
  const ::flatbuffers::String *action_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION_TYPE);
  }
  const ::flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<ArcaneWire::UUID>(verifier, VT_ENTITY_ID, 8) &&
           VerifyOffsetRequired(verifier, VT_ACTION_TYPE) &&
           verifier.VerifyString(action_type()) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
  GameActionPayloadT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GameActionPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GameActionPayload> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GameActionPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GameActionPayloadBuilder {
  typedef GameActionPayload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(const ArcaneWire::UUID *entity_id) {
    fbb_.AddStruct(GameActionPayload::VT_ENTITY_ID, entity_id);
  }
  void add_action_type(::flatbuffers::Offset<::flatbuffers::String> action_type) {
    fbb_.AddOffset(GameActionPayload::VT_ACTION_TYPE, action_type);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(GameActionPayload::VT_PAYLOAD, payload);
  }
  explicit GameActionPayloadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameActionPayload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameActionPayload>(end);
    fbb_.Required(o, GameActionPayload::VT_ENTITY_ID);
    fbb_.Required(o, GameActionPayload::VT_ACTION_TYPE);
    return o;
  }
};

inline ::flatbuffers::Offset<GameActionPayload> CreateGameActionPayload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    ::flatbuffers::Offset<::flatbuffers::String> action_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload = 0) {
  GameActionPayloadBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_action_type(action_type);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameActionPayload> CreateGameActionPayloadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const ArcaneWire::UUID *entity_id = nullptr,
    const char *action_type = nullptr,
    const std::vector<uint8_t> *payload = nullptr) {
  auto action_type__ = action_type ? _fbb.CreateString(action_type) : 0;
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return ArcaneWire::CreateGameActionPayload(
      _fbb,
      entity_id,
      action_type__,
      payload__);
}

::flatbuffers::Offset<GameActionPayload> CreateGameActionPayload(::flatbuffers::FlatBufferBuilder &_fbb, const GameActionPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClientFrameT : public ::flatbuffers::NativeTable {
  typedef ClientFrame TableType;
  ArcaneWire::ClientPayloadUnion payload{};
};

struct ClientFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientFrameT NativeTableType;
  typedef ClientFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  ArcaneWire::ClientPayload payload_type() const {
    return static_cast<ArcaneWire::ClientPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const ArcaneWire::PlayerStatePayload *payload_as_PlayerState() const {
    return payload_type() == ArcaneWire::ClientPayload_PlayerState ? static_cast<const ArcaneWire::PlayerStatePayload *>(payload()) : nullptr;
  }
  const ArcaneWire::GameActionPayload *payload_as_Action() const {
    return payload_type() == ArcaneWire::ClientPayload_Action ? static_cast<const ArcaneWire::GameActionPayload *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyClientPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  ClientFrameT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClientFrameT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ClientFrame> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientFrameT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const ArcaneWire::PlayerStatePayload *ClientFrame::payload_as<ArcaneWire::PlayerStatePayload>() const {
  return payload_as_PlayerState();
}

template<> inline const ArcaneWire::GameActionPayload *ClientFrame::payload_as<ArcaneWire::GameActionPayload>() const {
  return payload_as_Action();
}

struct ClientFrameBuilder {
  typedef ClientFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(ArcaneWire::ClientPayload payload_type) {
    fbb_.AddElement<uint8_t>(ClientFrame::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ClientFrame::VT_PAYLOAD, payload);
  }
  explicit ClientFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientFrame>(end);
    fbb_.Required(o, ClientFrame::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientFrame> CreateClientFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ArcaneWire::ClientPayload payload_type = ArcaneWire::ClientPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ClientFrameBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<ClientFrame> CreateClientFrame(::flatbuffers::FlatBufferBuilder &_fbb, const ClientFrameT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ServerFrameT : public ::flatbuffers::NativeTable {
  typedef ServerFrame TableType;
  ArcaneWire::ServerPayloadUnion payload{};
};

struct ServerFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerFrameT NativeTableType;
  typedef ServerFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  ArcaneWire::ServerPayload payload_type() const {
    return static_cast<ArcaneWire::ServerPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const ArcaneWire::DeltaPayload *payload_as_Delta() const {
    return payload_type() == ArcaneWire::ServerPayload_Delta ? static_cast<const ArcaneWire::DeltaPayload *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyServerPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
  ServerFrameT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ServerFrameT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ServerFrame> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerFrameT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const ArcaneWire::DeltaPayload *ServerFrame::payload_as<ArcaneWire::DeltaPayload>() const {
  return payload_as_Delta();
}

struct ServerFrameBuilder {
  typedef ServerFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(ArcaneWire::ServerPayload payload_type) {
    fbb_.AddElement<uint8_t>(ServerFrame::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ServerFrame::VT_PAYLOAD, payload);
  }
  explicit ServerFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerFrame>(end);
    fbb_.Required(o, ServerFrame::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerFrame> CreateServerFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ArcaneWire::ServerPayload payload_type = ArcaneWire::ServerPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ServerFrameBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

::flatbuffers::Offset<ServerFrame> CreateServerFrame(::flatbuffers::FlatBufferBuilder &_fbb, const ServerFrameT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline EntityStateT::EntityStateT(const EntityStateT &o)
      : entity_id((o.entity_id) ? new ArcaneWire::UUID(*o.entity_id) : nullptr),
        cluster_id((o.cluster_id) ? new ArcaneWire::UUID(*o.cluster_id) : nullptr),
        position((o.position) ? new ArcaneWire::Vec3Q(*o.position) : nullptr),
        velocity((o.velocity) ? new ArcaneWire::Vec3Q(*o.velocity) : nullptr),
        user_data(o.user_data),
        client_seq(o.client_seq) {
}

inline EntityStateT &EntityStateT::operator=(EntityStateT o) FLATBUFFERS_NOEXCEPT {
  std::swap(entity_id, o.entity_id);
  std::swap(cluster_id, o.cluster_id);
  std::swap(position, o.position);
  std::swap(velocity, o.velocity);
  std::swap(user_data, o.user_data);
  std::swap(client_seq, o.client_seq);
  return *this;
}

inline EntityStateT *EntityState::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EntityStateT>(new EntityStateT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EntityState::UnPackTo(EntityStateT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = entity_id(); if (_e) _o->entity_id = std::unique_ptr<ArcaneWire::UUID>(new ArcaneWire::UUID(*_e)); }
  { auto _e = cluster_id(); if (_e) _o->cluster_id = std::unique_ptr<ArcaneWire::UUID>(new ArcaneWire::UUID(*_e)); }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ArcaneWire::Vec3Q>(new ArcaneWire::Vec3Q(*_e)); }
  { auto _e = velocity(); if (_e) _o->velocity = std::unique_ptr<ArcaneWire::Vec3Q>(new ArcaneWire::Vec3Q(*_e)); }
  { auto _e = user_data(); if (_e) { _o->user_data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->user_data.begin()); } }
  { auto _e = client_seq(); _o->client_seq = _e; }
}

inline ::flatbuffers::Offset<EntityState> CreateEntityState(::flatbuffers::FlatBufferBuilder &_fbb, const EntityStateT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return EntityState::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EntityState> EntityState::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EntityStateT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EntityStateT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _entity_id = _o->entity_id ? _o->entity_id.get() : nullptr;
  auto _cluster_id = _o->cluster_id ? _o->cluster_id.get() : nullptr;
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _velocity = _o->velocity ? _o->velocity.get() : nullptr;
  auto _user_data = _o->user_data.size() ? _fbb.CreateVector(_o->user_data) : 0;
  auto _client_seq = _o->client_seq;
  return ArcaneWire::CreateEntityState(
      _fbb,
      _entity_id,
      _cluster_id,
      _position,
      _velocity,
      _user_data,
      _client_seq);
}

inline DeltaPayloadT::DeltaPayloadT(const DeltaPayloadT &o)
      : source_cluster_id((o.source_cluster_id) ? new ArcaneWire::UUID(*o.source_cluster_id) : nullptr),
        seq(o.seq),
        tick(o.tick),
        timestamp(o.timestamp),
        entity_data(o.entity_data),
        entity_offsets(o.entity_offsets),
        removed(o.removed) {
}

inline DeltaPayloadT &DeltaPayloadT::operator=(DeltaPayloadT o) FLATBUFFERS_NOEXCEPT {
  std::swap(source_cluster_id, o.source_cluster_id);
  std::swap(seq, o.seq);
  std::swap(tick, o.tick);
  std::swap(timestamp, o.timestamp);
  std::swap(entity_data, o.entity_data);
  std::swap(entity_offsets, o.entity_offsets);
  std::swap(removed, o.removed);
  return *this;
}

inline DeltaPayloadT *DeltaPayload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DeltaPayloadT>(new DeltaPayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DeltaPayload::UnPackTo(DeltaPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source_cluster_id(); if (_e) _o->source_cluster_id = std::unique_ptr<ArcaneWire::UUID>(new ArcaneWire::UUID(*_e)); }
  { auto _e = seq(); _o->seq = _e; }
  { auto _e = tick(); _o->tick = _e; }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = entity_data(); if (_e) { _o->entity_data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->entity_data.begin()); } }
  { auto _e = entity_offsets(); if (_e) { _o->entity_offsets.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->entity_offsets[_i] = _e->Get(_i); } } else { _o->entity_offsets.resize(0); } }
  { auto _e = removed(); if (_e) { _o->removed.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->removed[_i] = *_e->Get(_i); } } else { _o->removed.resize(0); } }
}

inline ::flatbuffers::Offset<DeltaPayload> CreateDeltaPayload(::flatbuffers::FlatBufferBuilder &_fbb, const DeltaPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DeltaPayload::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DeltaPayload> DeltaPayload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeltaPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DeltaPayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source_cluster_id = _o->source_cluster_id ? _o->source_cluster_id.get() : nullptr;
  auto _seq = _o->seq;
  auto _tick = _o->tick;
  auto _timestamp = _o->timestamp;
  auto _entity_data = _o->entity_data.size() ? _fbb.CreateVector(_o->entity_data) : 0;
  auto _entity_offsets = _o->entity_offsets.size() ? _fbb.CreateVector(_o->entity_offsets) : 0;
  auto _removed = _o->removed.size() ? _fbb.CreateVectorOfStructs(_o->removed) : 0;
  return ArcaneWire::CreateDeltaPayload(
      _fbb,
      _source_cluster_id,
      _seq,
      _tick,
      _timestamp,
      _entity_data,
      _entity_offsets,
      _removed);
}

inline PlayerStatePayloadT::PlayerStatePayloadT(const PlayerStatePayloadT &o)
      : entity_id((o.entity_id) ? new ArcaneWire::UUID(*o.entity_id) : nullptr),
        position((o.position) ? new ArcaneWire::Vec3Q(*o.position) : nullptr),
        velocity((o.velocity) ? new ArcaneWire::Vec3Q(*o.velocity) : nullptr),
        user_data(o.user_data),
        client_seq(o.client_seq) {
}

inline PlayerStatePayloadT &PlayerStatePayloadT::operator=(PlayerStatePayloadT o) FLATBUFFERS_NOEXCEPT {
  std::swap(entity_id, o.entity_id);
  std::swap(position, o.position);
  std::swap(velocity, o.velocity);
  std::swap(user_data, o.user_data);
  std::swap(client_seq, o.client_seq);
  return *this;
}

inline PlayerStatePayloadT *PlayerStatePayload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PlayerStatePayloadT>(new PlayerStatePayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PlayerStatePayload::UnPackTo(PlayerStatePayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = entity_id(); if (_e) _o->entity_id = std::unique_ptr<ArcaneWire::UUID>(new ArcaneWire::UUID(*_e)); }
  { auto _e = position(); if (_e) _o->position = std::unique_ptr<ArcaneWire::Vec3Q>(new ArcaneWire::Vec3Q(*_e)); }
  { auto _e = velocity(); if (_e) _o->velocity = std::unique_ptr<ArcaneWire::Vec3Q>(new ArcaneWire::Vec3Q(*_e)); }
  { auto _e = user_data(); if (_e) { _o->user_data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->user_data.begin()); } }
  { auto _e = client_seq(); _o->client_seq = _e; }
}

inline ::flatbuffers::Offset<PlayerStatePayload> CreatePlayerStatePayload(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerStatePayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return PlayerStatePayload::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PlayerStatePayload> PlayerStatePayload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PlayerStatePayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PlayerStatePayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _entity_id = _o->entity_id ? _o->entity_id.get() : nullptr;
  auto _position = _o->position ? _o->position.get() : nullptr;
  auto _velocity = _o->velocity ? _o->velocity.get() : nullptr;
  auto _user_data = _o->user_data.size() ? _fbb.CreateVector(_o->user_data) : 0;
  auto _client_seq = _o->client_seq;
  return ArcaneWire::CreatePlayerStatePayload(
      _fbb,
      _entity_id,
      _position,
      _velocity,
      _user_data,
      _client_seq);
}

inline GameActionPayloadT::GameActionPayloadT(const GameActionPayloadT &o)
      : entity_id((o.entity_id) ? new ArcaneWire::UUID(*o.entity_id) : nullptr),
        action_type(o.action_type),
        payload(o.payload) {
}

inline GameActionPayloadT &GameActionPayloadT::operator=(GameActionPayloadT o) FLATBUFFERS_NOEXCEPT {
  std::swap(entity_id, o.entity_id);
  std::swap(action_type, o.action_type);
  std::swap(payload, o.payload);
  return *this;
}

inline GameActionPayloadT *GameActionPayload::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<GameActionPayloadT>(new GameActionPayloadT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GameActionPayload::UnPackTo(GameActionPayloadT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = entity_id(); if (_e) _o->entity_id = std::unique_ptr<ArcaneWire::UUID>(new ArcaneWire::UUID(*_e)); }
  { auto _e = action_type(); if (_e) _o->action_type = _e->str(); }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->payload.begin()); } }
}

inline ::flatbuffers::Offset<GameActionPayload> CreateGameActionPayload(::flatbuffers::FlatBufferBuilder &_fbb, const GameActionPayloadT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return GameActionPayload::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GameActionPayload> GameActionPayload::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GameActionPayloadT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GameActionPayloadT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _entity_id = _o->entity_id ? _o->entity_id.get() : nullptr;
  auto _action_type = _fbb.CreateString(_o->action_type);
  auto _payload = _o->payload.size() ? _fbb.CreateVector(_o->payload) : 0;
  return ArcaneWire::CreateGameActionPayload(
      _fbb,
      _entity_id,
      _action_type,
      _payload);
}

inline ClientFrameT *ClientFrame::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClientFrameT>(new ClientFrameT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ClientFrame::UnPackTo(ClientFrameT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = ArcaneWire::ClientPayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<ClientFrame> CreateClientFrame(::flatbuffers::FlatBufferBuilder &_fbb, const ClientFrameT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ClientFrame::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ClientFrame> ClientFrame::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClientFrameT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClientFrameT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return ArcaneWire::CreateClientFrame(
      _fbb,
      _payload_type,
      _payload);
}

inline ServerFrameT *ServerFrame::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ServerFrameT>(new ServerFrameT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ServerFrame::UnPackTo(ServerFrameT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = payload_type(); _o->payload.type = _e; }
  { auto _e = payload(); if (_e) _o->payload.value = ArcaneWire::ServerPayloadUnion::UnPack(_e, payload_type(), _resolver); }
}

inline ::flatbuffers::Offset<ServerFrame> CreateServerFrame(::flatbuffers::FlatBufferBuilder &_fbb, const ServerFrameT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return ServerFrame::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ServerFrame> ServerFrame::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ServerFrameT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ServerFrameT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _payload_type = _o->payload.type;
  auto _payload = _o->payload.Pack(_fbb);
  return ArcaneWire::CreateServerFrame(
      _fbb,
      _payload_type,
      _payload);
}

template <bool B>
inline bool VerifyClientPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ClientPayload type) {
  switch (type) {
    case ClientPayload_NONE: {
      return true;
    }
    case ClientPayload_PlayerState: {
      auto ptr = reinterpret_cast<const ArcaneWire::PlayerStatePayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_Action: {
      auto ptr = reinterpret_cast<const ArcaneWire::GameActionPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyClientPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyClientPayload(
        verifier,  values->Get(i), types->GetEnum<ClientPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *ClientPayloadUnion::UnPack(const void *obj, ClientPayload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case ClientPayload_PlayerState: {
      auto ptr = reinterpret_cast<const ArcaneWire::PlayerStatePayload *>(obj);
      return ptr->UnPack(resolver);
    }
    case ClientPayload_Action: {
      auto ptr = reinterpret_cast<const ArcaneWire::GameActionPayload *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> ClientPayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case ClientPayload_PlayerState: {
      auto ptr = reinterpret_cast<const ArcaneWire::PlayerStatePayloadT *>(value);
      return CreatePlayerStatePayload(_fbb, ptr, _rehasher).Union();
    }
    case ClientPayload_Action: {
      auto ptr = reinterpret_cast<const ArcaneWire::GameActionPayloadT *>(value);
      return CreateGameActionPayload(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline ClientPayloadUnion::ClientPayloadUnion(const ClientPayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case ClientPayload_PlayerState: {
      value = new ArcaneWire::PlayerStatePayloadT(*reinterpret_cast<ArcaneWire::PlayerStatePayloadT *>(u.value));
      break;
    }
    case ClientPayload_Action: {
      value = new ArcaneWire::GameActionPayloadT(*reinterpret_cast<ArcaneWire::GameActionPayloadT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void ClientPayloadUnion::Reset() {
  switch (type) {
    case ClientPayload_PlayerState: {
      auto ptr = reinterpret_cast<ArcaneWire::PlayerStatePayloadT *>(value);
      delete ptr;
      break;
    }
    case ClientPayload_Action: {
      auto ptr = reinterpret_cast<ArcaneWire::GameActionPayloadT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = ClientPayload_NONE;
}

template <bool B>
inline bool VerifyServerPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ServerPayload type) {
  switch (type) {
    case ServerPayload_NONE: {
      return true;
    }
    case ServerPayload_Delta: {
      auto ptr = reinterpret_cast<const ArcaneWire::DeltaPayload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyServerPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyServerPayload(
        verifier,  values->Get(i), types->GetEnum<ServerPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline void *ServerPayloadUnion::UnPack(const void *obj, ServerPayload type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case ServerPayload_Delta: {
      auto ptr = reinterpret_cast<const ArcaneWire::DeltaPayload *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> ServerPayloadUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case ServerPayload_Delta: {
      auto ptr = reinterpret_cast<const ArcaneWire::DeltaPayloadT *>(value);
      return CreateDeltaPayload(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline ServerPayloadUnion::ServerPayloadUnion(const ServerPayloadUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case ServerPayload_Delta: {
      value = new ArcaneWire::DeltaPayloadT(*reinterpret_cast<ArcaneWire::DeltaPayloadT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void ServerPayloadUnion::Reset() {
  switch (type) {
    case ServerPayload_Delta: {
      auto ptr = reinterpret_cast<ArcaneWire::DeltaPayloadT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = ServerPayload_NONE;
}

inline const ArcaneWire::ServerFrame *GetServerFrame(const void *buf) {
  return ::flatbuffers::GetRoot<ArcaneWire::ServerFrame>(buf);
}

inline const ArcaneWire::ServerFrame *GetSizePrefixedServerFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ArcaneWire::ServerFrame>(buf);
}

template <bool B = false>
inline bool VerifyServerFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ArcaneWire::ServerFrame>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedServerFrameBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ArcaneWire::ServerFrame>(nullptr);
}

inline void FinishServerFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ArcaneWire::ServerFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedServerFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ArcaneWire::ServerFrame> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<ArcaneWire::ServerFrameT> UnPackServerFrame(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<ArcaneWire::ServerFrameT>(GetServerFrame(buf)->UnPack(res));
}

inline std::unique_ptr<ArcaneWire::ServerFrameT> UnPackSizePrefixedServerFrame(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<ArcaneWire::ServerFrameT>(GetSizePrefixedServerFrame(buf)->UnPack(res));
}

}  // namespace ArcaneWire

#endif  // FLATBUFFERS_GENERATED_ARCANEWIRE_ARCANEWIRE_H_
