// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/EntityType.g.h"
#include "SetEntities.g.generated.h"

// Reducer arguments struct for SetEntities
USTRUCT(BlueprintType)
struct ARCANEDEMO_API FSetEntitiesArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FEntityType> Entities;

    FSetEntitiesArgs() = default;

    FSetEntitiesArgs(const TArray<FEntityType>& InEntities)
        : Entities(InEntities)
    {}


    FORCEINLINE bool operator==(const FSetEntitiesArgs& Other) const
    {
        return Entities == Other.Entities;
    }
    FORCEINLINE bool operator!=(const FSetEntitiesArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FSetEntitiesArgs, Entities);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class ARCANEDEMO_API USetEntitiesReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FEntityType> Entities;

};


