// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "EntityType.g.generated.h"

USTRUCT(BlueprintType)
struct ARCANEDEMO_API FEntityType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBUuid EntityId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double X = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Y = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Z = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Vx = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Vy = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double Vz = 0.0;

    FORCEINLINE bool operator==(const FEntityType& Other) const
    {
        return EntityId == Other.EntityId && X == Other.X && Y == Other.Y && Z == Other.Z && Vx == Other.Vx && Vy == Other.Vy && Vz == Other.Vz;
    }

    FORCEINLINE bool operator!=(const FEntityType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FEntityType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param EntityType The FEntityType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FEntityType& EntityType)
{
    uint32 Hash = GetTypeHash(EntityType.EntityId);
    Hash = HashCombine(Hash, GetTypeHash(EntityType.X));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Y));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Z));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Vx));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Vy));
    Hash = HashCombine(Hash, GetTypeHash(EntityType.Vz));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FEntityType);

    UE_SPACETIMEDB_STRUCT(FEntityType, EntityId, X, Y, Z, Vx, Vy, Vz);
}
