// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerInputArgs {
    pub entity_id: __sdk::Uuid,
    pub dir_x: f64,
    pub dir_z: f64,
}

impl From<UpdatePlayerInputArgs> for super::Reducer {
    fn from(args: UpdatePlayerInputArgs) -> Self {
        Self::UpdatePlayerInput {
            entity_id: args.entity_id,
            dir_x: args.dir_x,
            dir_z: args.dir_z,
        }
    }
}

impl __sdk::InModule for UpdatePlayerInputArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_input {
    fn update_player_input(&self, entity_id: __sdk::Uuid, dir_x: f64, dir_z: f64) -> __sdk::Result<()> {
        self.update_player_input_then(entity_id, dir_x, dir_z, |_, _| {})
    }

    fn update_player_input_then(
        &self,
        entity_id: __sdk::Uuid,
        dir_x: f64,
        dir_z: f64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_input for super::RemoteReducers {
    fn update_player_input_then(
        &self,
        entity_id: __sdk::Uuid,
        dir_x: f64,
        dir_z: f64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdatePlayerInputArgs {
                entity_id,
                dir_x,
                dir_z,
            },
            callback,
        )
    }
}
